# Generated by Django 4.2.6 on 2024-10-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceConfigurationParameterName",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DoctorConfigurationParameterName",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DoctorConfigurationParameterValue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255)),
                (
                    "param",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.doctorconfigurationparametername",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_id", models.IntegerField()),
                (
                    "param",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.doctorconfigurationparametername",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.doctorconfigurationparametervalue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceConfigurationParameterValue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255)),
                (
                    "param",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.deviceconfigurationparametername",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_id", models.IntegerField()),
                (
                    "param",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.deviceconfigurationparametername",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.deviceconfigurationparametervalue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfigurationPairings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_id", models.IntegerField()),
                (
                    "device_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.deviceconfiguration",
                    ),
                ),
                (
                    "doctor_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.doctorconfiguration",
                    ),
                ),
            ],
        ),
    ]
